# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2b1dfb676667ce18a282fd30809cabd"
application_url = "https://portal.ksadrop.com/embedded/shopify"
embedded = true
name = "KSADrop Portal"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://portal.ksadrop.com/webhooks/shopify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://portal.ksadrop.com/shopify/callback" ]
