<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Every parcel an inventory manager scanned at the warehouse: OUT when it
     * leaves, IN when it comes back. Append-only — the parcel's newest row
     * says where it is now, and stock_scan_items holds what each scan did to
     * stock.
     */
    public function up(): void
    {
        Schema::create('stock_scans', function (Blueprint $table) {
            $table->id();
            $table->foreignId('shipment_id')->constrained()->cascadeOnDelete();
            $table->foreignId('order_id')->nullable()->constrained()->nullOnDelete();

            $table->string('direction', 3); // out | in

            // The inventory manager who scanned it.
            $table->foreignId('rider_id')->nullable()->constrained()->nullOnDelete();
            // The rider holding the parcel at that moment, if any: who it
            // came back from on an IN.
            $table->foreignId('parcel_rider_id')->nullable()->constrained('riders')->nullOnDelete();

            // Units in the parcel, matched to a product or not.
            $table->unsignedInteger('pieces')->default(0);
            $table->string('entry_method', 10)->nullable(); // camera | manual

            // Phone clock at the moment of the scan; created_at is when the
            // server received it.
            $table->timestamp('occurred_at');

            // Generated by the app per scan. A retried request (flaky signal,
            // double tap) carries the same one and counts once.
            $table->uuid('client_uuid')->unique();

            $table->timestamps();

            $table->index(['shipment_id', 'id']);
            $table->index(['rider_id', 'occurred_at']);
            $table->index('occurred_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('stock_scans');
    }
};
