<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Append-only log of every status update made by our own people (riders
     * today; hub and admin actions later). shipments.tracking_history keeps a
     * public-safe copy for the /track page — GPS, photos and COD details stay
     * here only.
     */
    public function up(): void
    {
        Schema::create('shipment_events', function (Blueprint $table) {
            $table->id();
            $table->foreignId('shipment_id')->constrained()->cascadeOnDelete();
            $table->foreignId('rider_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();

            $table->string('action', 40);
            $table->string('status_before', 30)->nullable();
            $table->string('status_after', 30);
            $table->string('reason', 40)->nullable();
            $table->text('note')->nullable();

            $table->decimal('cod_amount', 10, 2)->nullable();
            $table->string('payment_method', 20)->nullable();
            $table->string('recipient_name')->nullable();
            $table->string('photo_path')->nullable();

            $table->decimal('lat', 10, 7)->nullable();
            $table->decimal('lng', 10, 7)->nullable();
            $table->unsignedInteger('accuracy_m')->nullable();
            $table->string('entry_method', 10)->nullable(); // camera | manual

            // Phone clock at the moment of the update; created_at is when the
            // server received it. They differ once offline sync lands.
            $table->timestamp('occurred_at');

            // Generated by the app per update. A retried request (flaky
            // signal, double tap) carries the same one and is recorded once.
            $table->uuid('client_uuid')->unique();

            $table->timestamps();

            $table->index(['shipment_id', 'created_at']);
            $table->index(['rider_id', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('shipment_events');
    }
};
