<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Money a rider handed in to KSA Drop against the COD cash they
     * collected. What a rider still owes is never stored: it is their cash
     * collections (shipment_events) minus these — see
     * App\Services\Riders\RiderCash.
     *
     * Rows are never edited or deleted. A mistake is voided, with who and
     * why, and entered again.
     */
    public function up(): void
    {
        Schema::create('rider_payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('rider_id')->constrained()->cascadeOnDelete();
            $table->decimal('amount', 10, 2);
            // How the rider paid KSA Drop: cash | bank_transfer | other.
            $table->string('method', 20);
            $table->string('reference', 100)->nullable();
            $table->text('note')->nullable();
            // When the money was received; created_at is when it was entered.
            $table->timestamp('received_at');
            $table->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamp('voided_at')->nullable();
            $table->foreignId('voided_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('void_reason')->nullable();

            // Generated by the form per entry. A double click or a retried
            // request carries the same one and is recorded once.
            $table->uuid('client_uuid')->unique();

            $table->timestamps();

            $table->index(['rider_id', 'received_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('rider_payments');
    }
};
